### PR TITLE
FIX(.megamenu-menu-panel): give megamenu menu panel a dacker color

### PR DESCRIPTION
**Pull request by 1216892614**
give megamenu menu panel a dacker color

### CODE REVIEW

**Review by andredelft — CHANGES_REQUESTED** [review]
Thanks for this submission! I'm willing to merge this (if you fix the indentation), although I must say: I don't know what the megamenu is. Is it a Windows thing? I'm a Mac user. If so, could you provide a screenshot of the old menu, showing the issue, and a screenshot of the megamenu with the colors you propose?

Best,

André

**Comment by 1216892614** [comment]
All fixed. Add a prettierrc incase.

**Comment by andredelft** [comment]
Thank you for the screenshots, it looks good. Only issue is that the file `tailwind-dark.css` still has indentation 4 instead of 2. If you could fix that as well, then I will merge this. I think that will also solve the merge conflict.

(I am not able to edit the PR myself, since it is from your fork.)

**Comment by 1216892614** [comment]
> Thank you for the screenshots, it looks good. Only issue is that the file `tailwind-dark.css` still has indentation 4 instead of 2. If you could fix that as well, then I will merge this. I think that will also solve the merge conflict.
> 
> (I am not able to edit the PR myself, since it is from your fork.)

Sorry, I made a mistake in formatting the code. Everything should be fine now.

**Review by andredelft — APPROVED** [review]

**Pull request merged**
